stages:
    - package
    - build   
    - deploy
    - test

services:
    - docker:dind 
 
variables:
    DOCKER_DRIVER: overlay2 
    DOCKER_TLS_CERTDIR: ""


################################################################################################################

.package_job:
    stage: package
    image: maven:latest
    script: 
        - mvn -f user-service/pom.xml clean package
        
        
    tags: 
        - Docker_Runner
    artifacts:
        paths:
            - user-service/target/    
    rules: 
        - when: manual    

################################################################################################################

docker_build_user:
    stage: build
    image: docker:latest
    before_script:
        - docker build -t user_app:latest -f Dockerfile.user .
        
    script:
        - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
        - docker tag user_app:latest registry.gitlab.com/hamrashilar/spring/user_app:latest 
        - docker push registry.gitlab.com/hamrashilar/spring/user_app:latest
    tags:
        - Kubernetes 
    rules:
        - when: manual

################################################################################################################

.k8s_auth: &kubeauth
  - export KUBE_VERSION=$(curl https://storage.googleapis.com/kubernetes-release/release/stable.txt)
  - echo $KUBE_VERSION
  - curl -o /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/"${KUBE_VERSION}"/bin/linux/amd64/kubectl
  - chmod a+x /usr/local/bin/kubectl
  - mkdir -p ~/.kube
  - cat $KUBE_CONFIG > ~/.kube/config
  - chown $(id -u):$(id -g) $HOME/.kube/config
  # Change Ip address and master hostname
  - echo "192.168.94.17 kubemaster" >>/etc/hosts 

################################################################################################################

docker_build_product:
    stage: build
    image: docker:latest
    before_script:
        - docker build -t product_app:latest -f Dockerfile.product .
        
    script:
        - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
        - docker tag product_app:latest registry.gitlab.com/hamrashilar/spring/product_app:latest 
        - docker push registry.gitlab.com/hamrashilar/spring/product_app:latest
    tags:
        - Kubernetes 
    rules:
        - when: manual    
        
################################################################################################################

docker_build_front_end:
    stage: build
    image: docker:latest
    before_script:
        - docker build -t front_end:latest -f Dockerfile.frontend .
        
    script:
        - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
        - docker tag front_end:latest registry.gitlab.com/hamrashilar/spring/front_end:latest 
        - docker push registry.gitlab.com/hamrashilar/spring/front_end:latest
    tags:
        - Kubernetes 
    rules:
        - when: manual

################################################################################################################        

kubernetes_deploy:
  stage: deploy
  image: alpine:latest  
  before_script:
      - apk add curl
      - *kubeauth
      - kubectl get nodes
        
  script:
      - kubectl apply -f k8s/product_app_deployment.yaml
      - kubectl apply -f k8s/user_app_deployment.yaml    
      - kubectl apply -f k8s/front_end_deployment.yaml
      - kubectl apply -f k8s/product_service.yaml
      - kubectl apply -f k8s/user_service.yaml
      - kubectl apply -f k8s/front_end_service.yaml

  tags:
    - Kubernetes
  #rules:
  #    - when: manual  

################################################################################################################


.test_job:
    image: 
    stage: test
    script:
        - echo "Testing...."
        - ls -R user-service/target/
    tags:
        - Docker_Runner    
    rules:
        - when: manual    