stages:
    - package
    - build   
    - test

package_job:
    stage: package
    image: maven:latest
    script: 
        - mvn -f user-service/pom.xml clean package
        
        
    tags: 
        - Docker_Runner
    artifacts:
        paths:
            - user-service/target/    
    rules:
        - when: manual    

docker_build:
    stage: build
    image: docker:latest
    services:
        - name: docker:dind
    variables:
        DOCKER_DRIVER: "overlay2"
        DOCKER_TLS_CERTDIR: ""    
    
    before_script:
        
        - docker build -t java_app:latest .
        
    script:
        - docker run --rm java_app:latest
    tags:
        - Docker_Runner    

test_job:
    image: 
    stage: test
    script:
        - echo "Testing...."
        - ls -R user-service/target/
    tags:
        - Docker_Runner    
    rules:
        - when: manual    