stages:
    - build
    - test

package_job:
    image: maven:latest
    script:
        - echo "Packaging....."
        - mvn --version
        - mvn -f user-service/pom.xml clean package
    tags:
        - Docker
    artifacts:
        paths:
            - target/    
    rules:
        - when: manual    

test_job:
    script:
        - echo "Testing...."
        - ls target/*
    tags:
        - Docker    
    rules:
        - when: manual    