stages:
    - package
    - build   
    - test

.package_job:
    stage: package
    image: maven:latest
    script: 
        - mvn -f user-service/pom.xml clean package
        
        
    tags: 
        - Docker_Runner
    artifacts:
        paths:
            - user-service/target/    
    rules:
        - when: manual    

docker_build_user:
    stage: build
    image: docker:latest
    services:
        - name: docker:dind
    variables:
        DOCKER_DRIVER: "overlay2"
        DOCKER_TLS_CERTDIR: ""    
    
    before_script:
        - pwd
        - ls -l
        - docker build -t user_app:latest -f Dockerfile.product .
        
    script:
        - docker run -d user_app:latest 
    tags:
        - Kubernetes  
    

docker_build_product:
    stage: build
    image: docker:latest
    services:
        - name: docker:dind
    variables:
        DOCKER_DRIVER: "overlay2"
        DOCKER_TLS_CERTDIR: ""    
    
    before_script:
        - pwd
        - ls -l
        - docker build -t product_app:latest -f Dockerfile.user .
        
    script:
        - docker run -d product_app:latest 
    tags:
        - Kubernetes    
        


.test_job:
    image: 
    stage: test
    script:
        - echo "Testing...."
        - ls -R user-service/target/
    tags:
        - Docker_Runner    
    rules:
        - when: manual    