stages:
    - build
    - test

package_job:
    stage: build
    image: maven:latest
    script: 
        - mvn -f user-service/pom.xml clean package
        - ls -R user-service/target/
    tags: 
        - Docker_Runner
    artifacts:
        paths:
            - user-sevice/target/    
    rules:
        - when: manual    

test_job:
    stage: test
    script:
        - echo "Testing...."
        - ls -R user-service/target/
    tags:
        - Docker_Runner    
    rules:
        - when: manual    