stages:
    - build
    - test

package_job:
    stage: build
    image: maven:latest
    script:
        - mvn -f user-service/pom.xml clean package
    tags:
        - Docker
    artifacts:
        paths:
            - user-service/target/    
    rules:
        - when: manual    

test_job:
    stage: test
    script:
        - echo "Testing...."
        - ls user-service/target/*
    tags:
        - Docker    
    rules:
        - when: manual    