stages:
    - package
    - build   
    - deploy
    - test

services:
    - docker:dind

variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""


################################################################################################################

.package_job:
    stage: package
    image: maven:latest
    script: 
        - mvn -f user-service/pom.xml clean package
        
        
    tags: 
        - Docker_Runner
    artifacts:
        paths:
            - user-service/target/    
    rules:
        - when: manual    

################################################################################################################

.docker_build_user:
    stage: build
    image: docker:latest
    before_script:
        - docker build -t user_app:latest -f Dockerfile.product .
        
    script:
        - docker run -d user_app:latest 
    tags:
        - Kubernetes

################################################################################################################

.k8s_auth: &kubeauth
  - export KUBE_VERSION=$(curl https://storage.googleapis.com/kubernetes-release/release/stable.txt)
  - echo $KUBE_VERSION
  - curl -o /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/"${KUBE_VERSION}"/bin/linux/amd64/kubectl
  - chmod a+x /usr/local/bin/kubectl
  - mkdir -p ~/.kube
  - cat $KUBE_CONFIG > ~/.kube/config
  - chown $(id -u):$(id -g) $HOME/.kube/config
  # Change Ip address and master hostname
  - echo "192.168.94.17 kubemaster" >>/etc/hosts 

################################################################################################################

docker_build_product:
    stage: build
    image: docker:latest
    before_script:
        - docker build -t product_app:latest -f Dockerfile.user .
        
    script:
        - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
        - docker tag product_app:latest registry.gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/product_app:latest 
        - docker push registry.gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/product_app:latest
    tags:
        - Kubernetes 
    rules:
        - when: manual    
        
################################################################################################################

kubernetes_deploy:
  stage: deploy
  image: docker:latest  
  before_script:
      - kubectl get nodes
        
  script:
      - kubectl apply -f k8s/deployment.yaml    
  tags:
    - Kubernetes
  rules:
      - when: manual  

################################################################################################################


.test_job:
    image: 
    stage: test
    script:
        - echo "Testing...."
        - ls -R user-service/target/
    tags:
        - Docker_Runner    
    rules:
        - when: manual    