apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: user-app
          image: "registry.gitlab.com/Hamras Hilar A/spring/"  # This will be replaced by the CI/CD pipeline
          ports:
            - containerPort: 8080
