apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: front-end
  ports:
    - protocol: TCP
      port: 83
      targetPort: 8000
      nodePort: 30003
  type: NodePort