apiVersion: v1
kind: Service
metadata:
  name: product-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  selector:
    app: product-app
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8082
  type: LoadBalancer