apiVersion: v1
kind: Service
metadata:
  name: product-app-service
spec:
  selector:
    app: product-app
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8082
      nodePort: 30001
  type: NodePort