apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-app
  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
        - name: user-app
          image: registry.gitlab.com/hamrashilar/spring/product_app:latest  
          ports:
            - containerPort: 8082
