apiVersion: v1
kind: Service
metadata:
  name: user-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  selector:
    app: user-app
  ports:
    - protocol: TCP
      port: 82
      targetPort: 8081
  type: LoadBalancer